export const GET_BANNERS_REQUEST = 'GET_BANNERS_REQUEST'
export const GET_BANNERS_SUCCESS = 'GET_BANNERS_SUCCESS'
export const GET_BANNERS_FAILURE = 'GET_BANNERS_FAILURE'

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'

export const GET_MAIN_PRODUCTS_REQUEST = 'GET_MAIN_PRODUCTS_REQUEST'
export const GET_MAIN_PRODUCTS_SUCCESS = 'GET_MAIN_PRODUCTS_SUCCESS'
export const GET_MAIN_PRODUCTS_FAILURE = 'GET_MAIN_PRODUCTS_FAILURE'
